### ISSUE TITLE
import custom translation

### ISSUE THREAD

**Issue by kewran** [igrybkov/leosync#5]
Can you please make import from csv file generated by Chrome extension [anki-leo](https://github.com/troggy/anki-leo)? Or any other way to import a custom translation and picture?

**Comment by igrybkov** [comment]
Yes, I planned to add work with CSV, but cannot say when it would be done.
Can you clarify which functionality do you need? Why the functionality of anki-leo is not enough for your purposes?

**Comment by kewran** [comment]
anki-leo allow export full data to csv, but there is no way to import that csv into new account. I want merge 2 accounts into one.

**Comment by igrybkov** [comment]
Oh, I understand. It's a good point to add this support.
You can add it and send a pull request. It's easy to do as you already have an example of import from a list of words.
